name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: nvm install, npm install, build, and test
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        nvm install
        nvm use
        npm ci
        npm test
      working-directory: exercises/javascript
      env:
        CI: true
