name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v2.0.0
      working-directory: exercises/javascript
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
      working-directory: exercises/javascript
